import CodeBlock from '../components/CodeBlock';
import Callout from '../components/Callout';
import type { ChapterData } from './types';

export const architectureOverviewChapter: ChapterData = {
  id: 'architecture-overview',
  title: 'Architecture Overview',
  description:
    'Identify the architecture pattern and understand how the PHP daemon is organized around an event-driven agent loop.',
  files: ['src/AgentDaemon.php', 'bin/agent.php', 'index.ts', 'README.md', 'composer.json'],
  content: (
    <>
      <h2>What pattern does this codebase use?</h2>
      <p>
        <strong>sample-openclaw-agent-php</strong> uses an <strong>event-driven daemon architecture</strong> with a
        single orchestrator class (<code>AgentDaemon</code>). It is not classic MVC and not strict clean architecture;
        it is closer to a <strong>layered modular monolith</strong> where one process owns the runtime loop,
        integration adapters, and persistence boundaries.
      </p>

      <h3>High-level structure</h3>
      <ul>
        <li>
          <strong>Entry layer:</strong> <code>bin/agent.php</code> bootstraps Composer autoloading and starts the daemon.
        </li>
        <li>
          <strong>Core orchestration:</strong> <code>src/AgentDaemon.php</code> handles socket lifecycle,
          thread loops, tool dispatch, and heartbeat scheduling.
        </li>
        <li>
          <strong>External adapters:</strong> Slack APIs, Anthropic messages API, and WebSocket client are accessed through adapter-style methods.
        </li>
        <li>
          <strong>Runtime state + persistence:</strong> in-memory maps for active loops/pending messages plus on-disk thread JSON in
          <code>~/.picobot/threads</code>.
        </li>
      </ul>

      <CodeBlock
        filename="bin/agent.php"
        language="php"
        code={`#!/usr/bin/env php
<?php

declare(strict_types=1);

use SampleAgent\\AgentDaemon;

require dirname(__DIR__) . '/vendor/autoload.php';

$daemon = new AgentDaemon();
$daemon->run();`}
        caption="The runtime has one explicit entry point: instantiate AgentDaemon and call run()."
      />

      <h3>Daemon loop as architectural center</h3>
      <p>
        The <code>run()</code> method opens a Slack Socket Mode connection, receives envelopes, dispatches message
        events, and periodically triggers heartbeat checks. This loop-driven design is the core pattern.
      </p>

      <CodeBlock
        filename="src/AgentDaemon.php"
        language="php"
        code={`public function run(): void
{
    $this->validateEnvironment();
    $this->bootstrapWorkspace();
    chdir($this->workspaceDir);

    while (true) {
        $socket = $this->openSocketModeConnection();
        while (true) {
            if (time() >= $nextHeartbeatAt) {
                $this->runHeartbeatTick();
            }
            $payload = json_decode($socket->receive(), true);
            $this->handleSocketEnvelope($socket, $payload);
        }
    }
}`}
        caption="The daemon uses nested infinite loops: outer loop for reconnection, inner loop for event processing."
      />

      <Callout tone="tip" title="Architecture takeaway">
        The project deliberately keeps orchestration centralized in one class. That makes control flow easy to trace,
        while helper methods isolate concerns like API calls, tool execution, and filesystem safety.
      </Callout>

      <h3>Why include index.ts?</h3>
      <p>
        <code>index.ts</code> is the TypeScript reference implementation that inspired the PHP port. Studying both files
        reveals intentional parity: thread maps, tool-use loops, heartbeat behavior, and workspace prompt construction.
      </p>
    </>
  ),
  diagram: 'architecture',
  quiz: [
    {
      question: 'Which architecture style best describes sample-openclaw-agent-php?',
      options: [
        'MVC with controllers and views',
        'Event-driven daemon with layered modules',
        'Microservices over message queues',
        'Serverless functions only',
      ],
      correctIndex: 1,
      explanation:
        'The runtime is a long-lived daemon that reacts to Slack events and coordinates multiple layers inside one process.',
    },
    {
      question: 'What is the single executable entry point for the PHP daemon?',
      options: ['src/AgentDaemon.php', 'index.ts', 'bin/agent.php', 'composer.lock'],
      correctIndex: 2,
      explanation:
        'bin/agent.php loads the autoloader, creates AgentDaemon, and calls run().',
    },
    {
      question: 'Why is AgentDaemon considered the orchestration core?',
      options: [
        'It only stores constants',
        'It owns connection handling, thread loops, tools, and persistence calls',
        'It is generated by Composer',
        'It only validates environment variables',
      ],
      correctIndex: 1,
      explanation:
        'AgentDaemon coordinates the full runtime lifecycle: Slack, Anthropic, tool calls, heartbeats, and thread persistence.',
    },
  ],
};
